exec-once = waybar
exec-once = ~/.config/hypr/scripts/night-mode
exec-once = swww-daemon & swww img ~/pictures/wallpapers/reze.jpg
exec-once = echo "50" | sudo tee "/sys/class/power_supply/BAT0/charge_control_end_threshold" >/dev/null
